### ISSUE TITLE
.leaflet-yandex-layer position absolute

### ISSUE THREAD

**Issue by rendrom** [shramov/leaflet-plugins#260]
leaflet-plugins@3.0.0
leaflet@1.0.3

Yandex Layer container hide containers of plugins like 
https://github.com/w8r/Leaflet.Modal 
or 
https://github.com/Turbo87/leaflet-sidebar

Example
https://jsfiddle.net/rendrom/v7ctukak/2/

fix
https://jsfiddle.net/rendrom/v7ctukak/3/

```css
.leaflet-yandex-layer {
  position: absolute;
}
```
